import type { TarotSpread } from "./types";

export const TAROT_SPREADS: TarotSpread[] = [
  {
    id: "free",
    name: "Free Tarot",
    description: "Classic 10-card draw inspired by Edmond's tradition. See the full picture.",
    cardCount: 10,
    positions: [
      "Present situation",
      "Challenge",
      "Distant past",
      "Recent past",
      "Possible outcome",
      "Near future",
      "Your approach",
      "External influences",
      "Hopes & fears",
      "Final outcome",
    ],
    available: true,
    category: "tarot",
  },
  {
    id: "love",
    name: "Love Tarot",
    description: "Seven cards focused on your heart, connection, and romantic path.",
    cardCount: 7,
    positions: ["You", "Them", "Connection", "Challenge", "Advice", "Near future", "Outcome"],
    available: true,
    category: "tarot",
  },
  {
    id: "yes-no",
    name: "Yes / No Tarot",
    description: "One clear card for a direct question.",
    cardCount: 1,
    positions: ["Answer"],
    available: true,
    category: "tarot",
  },
  {
    id: "psychic",
    name: "Psychic Reading",
    description: "Five cards to reveal hidden influences and guidance.",
    cardCount: 5,
    positions: ["Root energy", "Hidden influence", "Present energy", "Guidance", "Outcome"],
    available: true,
    category: "tarot",
  },
  {
    id: "celtic-cross",
    name: "Celtic Cross",
    description: "The classic Celtic spread — deep insight into your situation.",
    cardCount: 10,
    positions: [
      "Heart of the matter",
      "Crossing influence",
      "Foundation",
      "Recent past",
      "Crown — best possible",
      "Near future",
      "Self",
      "Environment",
      "Hopes & fears",
      "Final outcome",
    ],
    available: true,
    category: "tarot",
  },
  {
    id: "daily",
    name: "Daily Tarot",
    description: "One card for today's energy and guidance.",
    cardCount: 1,
    positions: ["Today's message"],
    available: true,
    category: "daily",
  },
  {
    id: "oracle",
    name: "Oracle Cards",
    description: "Gentle oracle wisdom for reflection.",
    cardCount: 3,
    positions: ["Message", "Lesson", "Blessing"],
    available: true,
    category: "oracle",
  },
  {
    id: "angel",
    name: "Angel Tarot",
    description: "Comforting guidance from angelic energy.",
    cardCount: 3,
    positions: ["Protection", "Guidance", "Blessing"],
    available: true,
    category: "oracle",
  },
  {
    id: "osho",
    name: "Osho Tarot",
    description: "Zen-inspired cards for inner awareness.",
    cardCount: 3,
    positions: ["Awareness", "Transformation", "Celebration"],
    available: true,
    category: "oracle",
  },
  {
    id: "chinese",
    name: "Chinese Tarot",
    description: "Eastern symbolism and ancient wisdom.",
    cardCount: 5,
    positions: ["Earth", "Water", "Fire", "Wood", "Metal"],
    available: true,
    category: "oracle",
  },
  {
    id: "egyptian",
    name: "Egyptian Tarot",
    description: "Mystery of the pharaohs and sacred symbols.",
    cardCount: 5,
    positions: ["Ankh", "Scarab", "Eye", "Pyramid", "Nile"],
    available: true,
    category: "oracle",
  },
  {
    id: "32-cards",
    name: "32 Cards",
    description: "Traditional 32-card fortune telling deck.",
    cardCount: 5,
    positions: ["Past", "Present", "Hidden", "Advice", "Outcome"],
    available: true,
    category: "oracle",
  },
];

export function getSpreadById(id: string): TarotSpread | undefined {
  return TAROT_SPREADS.find((s) => s.id === id);
}
