import type { ZodiacSign } from "@/lib/astrology/zodiac-tokens";

export interface ZodiacSignMeta {
  sign: ZodiacSign;
  slug: string;
  dates: string;
  symbol: string;
  rulingPlanet: string;
  rulingPlanetSlug: string;
  traditionalRuler?: string;
  element: "Fire" | "Earth" | "Air" | "Water";
  modality: "Cardinal" | "Fixed" | "Mutable";
  compatibleWith: string[];
  challengingWith: string[];
}

export const ZODIAC_META: Record<ZodiacSign, ZodiacSignMeta> = {
  Aries: {
    sign: "Aries",
    slug: "aries",
    dates: "March 21 – April 19",
    symbol: "♈",
    rulingPlanet: "Mars",
    rulingPlanetSlug: "mars",
    element: "Fire",
    modality: "Cardinal",
    compatibleWith: ["leo", "sagittarius", "gemini", "aquarius"],
    challengingWith: ["cancer", "capricorn"],
  },
  Taurus: {
    sign: "Taurus",
    slug: "taurus",
    dates: "April 20 – May 20",
    symbol: "♉",
    rulingPlanet: "Venus",
    rulingPlanetSlug: "venus",
    element: "Earth",
    modality: "Fixed",
    compatibleWith: ["virgo", "capricorn", "cancer", "pisces"],
    challengingWith: ["leo", "aquarius"],
  },
  Gemini: {
    sign: "Gemini",
    slug: "gemini",
    dates: "May 21 – June 20",
    symbol: "♊",
    rulingPlanet: "Mercury",
    rulingPlanetSlug: "mercury",
    element: "Air",
    modality: "Mutable",
    compatibleWith: ["libra", "aquarius", "aries", "leo"],
    challengingWith: ["virgo", "pisces"],
  },
  Cancer: {
    sign: "Cancer",
    slug: "cancer",
    dates: "June 21 – July 22",
    symbol: "♋",
    rulingPlanet: "Moon",
    rulingPlanetSlug: "moon",
    element: "Water",
    modality: "Cardinal",
    compatibleWith: ["scorpio", "pisces", "taurus", "virgo"],
    challengingWith: ["aries", "libra"],
  },
  Leo: {
    sign: "Leo",
    slug: "leo",
    dates: "July 23 – August 22",
    symbol: "♌",
    rulingPlanet: "Sun",
    rulingPlanetSlug: "sun",
    element: "Fire",
    modality: "Fixed",
    compatibleWith: ["aries", "sagittarius", "gemini", "libra"],
    challengingWith: ["taurus", "scorpio"],
  },
  Virgo: {
    sign: "Virgo",
    slug: "virgo",
    dates: "August 23 – September 22",
    symbol: "♍",
    rulingPlanet: "Mercury",
    rulingPlanetSlug: "mercury",
    element: "Earth",
    modality: "Mutable",
    compatibleWith: ["taurus", "capricorn", "cancer", "scorpio"],
    challengingWith: ["gemini", "sagittarius"],
  },
  Libra: {
    sign: "Libra",
    slug: "libra",
    dates: "September 23 – October 22",
    symbol: "♎",
    rulingPlanet: "Venus",
    rulingPlanetSlug: "venus",
    element: "Air",
    modality: "Cardinal",
    compatibleWith: ["gemini", "aquarius", "leo", "sagittarius"],
    challengingWith: ["cancer", "capricorn"],
  },
  Scorpio: {
    sign: "Scorpio",
    slug: "scorpio",
    dates: "October 23 – November 21",
    symbol: "♏",
    rulingPlanet: "Pluto",
    rulingPlanetSlug: "pluto",
    traditionalRuler: "Mars",
    element: "Water",
    modality: "Fixed",
    compatibleWith: ["cancer", "pisces", "virgo", "capricorn"],
    challengingWith: ["leo", "aquarius"],
  },
  Sagittarius: {
    sign: "Sagittarius",
    slug: "sagittarius",
    dates: "November 22 – December 21",
    symbol: "♐",
    rulingPlanet: "Jupiter",
    rulingPlanetSlug: "jupiter",
    element: "Fire",
    modality: "Mutable",
    compatibleWith: ["aries", "leo", "libra", "aquarius"],
    challengingWith: ["virgo", "pisces"],
  },
  Capricorn: {
    sign: "Capricorn",
    slug: "capricorn",
    dates: "December 22 – January 19",
    symbol: "♑",
    rulingPlanet: "Saturn",
    rulingPlanetSlug: "saturn",
    element: "Earth",
    modality: "Cardinal",
    compatibleWith: ["taurus", "virgo", "scorpio", "pisces"],
    challengingWith: ["aries", "libra"],
  },
  Aquarius: {
    sign: "Aquarius",
    slug: "aquarius",
    dates: "January 20 – February 18",
    symbol: "♒",
    rulingPlanet: "Uranus",
    rulingPlanetSlug: "uranus",
    traditionalRuler: "Saturn",
    element: "Air",
    modality: "Fixed",
    compatibleWith: ["gemini", "libra", "aries", "sagittarius"],
    challengingWith: ["taurus", "scorpio"],
  },
  Pisces: {
    sign: "Pisces",
    slug: "pisces",
    dates: "February 19 – March 20",
    symbol: "♓",
    rulingPlanet: "Neptune",
    rulingPlanetSlug: "neptune",
    traditionalRuler: "Jupiter",
    element: "Water",
    modality: "Mutable",
    compatibleWith: ["cancer", "scorpio", "taurus", "capricorn"],
    challengingWith: ["gemini", "sagittarius"],
  },
};
